name: candle_setup_finder
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  bloc: ^8.1.4
  cron: ^0.6.1
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

  # path: ^1.8.0
